export enum ErrorType {
    LOGIN_ERROR = 'LOGIN_ERROR',
    EVALUATION_ERROR = 'EVALUATION_ERROR',
    SESSION_ERROR = 'SESSION_ERROR',
    SIGNUP_ERROR = 'SIGNUP_ERROR',
    CONNECTION_ERROR = 'CONNECTION_ERROR',
}